### PR TITLE
Made HttpGetVocabulary public, needed for another project.

### PR DESCRIPTION
**Pull request by cowclaw**
Needed for a university project, made the vocab public, just like most other vocabs are public.

### CODE REVIEW

**Comment by skodape** [comment]
@cowclaw May I ask for the motivation and semantic of the Configuration interface? 
For example there might be multiple configuration classes in the future (versioning, support for multiple vocabularies, ..) and then it's not clear which of these should implement the interface.

**Comment by cowclaw** [comment]
From a programming point of view it's always reasonable to have a common base for entities of the same kind. In this case the configurations. I would consider it even beeing a code smell if all classes end with a suffix Configuration without inheriting some common Configuration. 

For our university project, we use linkedpipes rest api. But not only. In order not to reinvent the wheel we e.g. use component configuration classes and the RdfToPojo type (we find configuration classes using reflection :-)). And to be able to handle these Configuration objects independent of their concrete implementation we need the common base.

**Comment by cowclaw** [comment]
Oh, the pull request automatically got updatet. I was wondering why you were reviewing code I didnt create a pull request for.

**Comment by skodape** [comment]
Yes as long as the pull request is open it gets automatically update with every change you made. As it is probably not what you intended - based on the comment, we can close the pull request. You can recreate it any time you would like to merge somethings.

I agree with making the vocabularies public - I've done this update f185f2f0e609297b45247dcf9104b27bff385646.

As to the configuration. The original intention was to "replace" the inheritance with some sort of a "naming convention". As the interface would be empty and used only to identify the configuration class, which could be done based on the naming convention. Still I think I can understand your point of view  and your use-case.

However I would still like to ask you about your projet. How do you use a configuration after you find it? The answer should provide us with possible documentation and purpose of the interface - ie. for example some restrictions like: use only once per component for main configuration class etc .. This might be important as for now each component have a single configuration, but that might change. Then it would be important to have a clear understanding of the original purpose to not misused the interface - which may lead to unintentional and unnecessary break of compatibility with your project.

**Pull request closed without merging**
